-- Create cluster_metadata table to store cluster characteristics and explanations
-- This table stores aggregate statistics and metadata for each cluster
-- Generated by k-means clustering script

CREATE TABLE IF NOT EXISTS cluster_metadata (
    cluster_id INT PRIMARY KEY,
    cluster_name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    avg_age DECIMAL(5,2),
    avg_income DECIMAL(10,2),
    avg_purchase_amount DECIMAL(10,2),
    customer_count INT,
    age_min INT,
    age_max INT,
    income_min DECIMAL(10,2),
    income_max DECIMAL(10,2),
    purchase_min DECIMAL(10,2),
    purchase_max DECIMAL(10,2),
    dominant_gender VARCHAR(20),
    dominant_region VARCHAR(50),
    business_recommendation TEXT,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Add indexes for better query performance
CREATE INDEX idx_cluster_name ON cluster_metadata(cluster_name);
